### ISSUE TITLE
대체이걸왜...세그로..

### ISSUE THREAD

**Issue by wolframhwang** [wolframhwang/Revengers#10]
https://github.com/wolframhwang/Revengers/blob/5fead033c86f104c0ef0e76aff44747c82126264/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98/%EA%B4%91%EA%B3%A0%20%EC%82%BD%EC%9E%85/sangdo_%EA%B4%91%EA%B3%A0%20%EC%82%BD%EC%9E%85('%EA%B7%B8%20%EB%B0%A9%EB%B2%95').kt#L3

**Comment by sangdo913** [comment]
헿!
다시 생각해서 풀었자나요!
